version: "3.9"

services:
  db:
    image: postgres:14
    container_name: banking_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banking_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d banking_db -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: banking_app
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/banking_db"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
